### PR TITLE
health check docs

### LINKED ISSUE #578: Probes - What to watch/monitor for a running cross DC setup and that none of the parts has failed
When customers run the setup in their environment, they should point their monitoring to specific URLs to see if everything is up and running as expected. 

Examples: 
* URL on loadbalancer
* URL on Keycloak Route (one on each Cluster)
* URL on Infinispan (one on each Cluster)
* URL on the Gossip Router
* ...

Those could be the health endpoints.

### PR DESCRIPTION
**Pull request by kami619**
fixes #578

### CODE REVIEW

File: provision/rosa-cross-dc/cross-site-health-checks.sh [hunk 1]
```diff
@@ -0,0 +1,126 @@
...
+health_check $infinispan_rest_url/rest/v2/cache-managers/default/health/status
+
+echo "Verify individual cache health"
+curl -u $infinispan_user:$infinispan_pwd -sk $infinispan_rest_url/rest/v2/cache-managers/default/health \
+ | jq 'if .cluster_health.health_status == "HEALTHY" and (all(.cache_health[].status; . == "HEALTHY")) then "HEALTHY" else "UNHEALTHY" end'
+echo
+
+echo "ISPN Cluster Distribution"
+curl -u $infinispan_user:$infinispan_pwd -sk $infinispan_rest_url/rest/v2/cluster\?action\=distribution \
+ | jq --argjson expectedCount $expected_count 'if map(select(.node_addresses | length > 0)) | length == $expectedCount then "HEALTHY" else "UNHEALTHY" end'
```
Comment (ryanemerson) [inline provision/rosa-cross-dc/cross-site-health-checks.sh:114]: I always get the following errors:

```bash
ISPN Cluster Distribution
jq: invalid JSON text passed to --argjson
Use jq --help for help with command-line options,
or see the jq manpage, or online docs  at https://stedolan.github.io/jq
```

**Review by ryanemerson — CHANGES_REQUESTED** [review]
Nice work @kami619, I just experienced a couple of issues.

File: provision/rosa-cross-dc/cross-site-health-checks.sh [hunk 2]
```diff
@@ -0,0 +1,126 @@
+#!/usr/bin/env bash
```
[the remark this answers is not in the document]
Comment (kami619) [reply provision/rosa-cross-dc/cross-site-health-checks.sh:1]: hmmmm, I think the changes got lost when I modified the filename, later on, I will fix this issue.

File: provision/rosa-cross-dc/cross-site-health-checks.sh (hunk 1 above)
Comment (kami619) [reply provision/rosa-cross-dc/cross-site-health-checks.sh:114]: I still need to add docs on the usage of the script, but an example way of utilizing this would need to establish a session to the openshift cluster from your terminal session, alternatively we can think of using the oc login script internally.

```
./cross-site-health-checks.sh -d gh-keycloak-a-gh-keycloak-b-masked.keycloak-benchmark.com \
-u developer -p masked \
-s gh-keycloak-a.masked.openshiftapps.com \
-c 3 -n runner-keycloak
```

let me know if that works for you.

Comment (ryanemerson) [reply provision/rosa-cross-dc/cross-site-health-checks.sh:114]: I had missed the `-c 3` arg, adding this fixed the issue :slightly_smiling_face: . We need to add this flag to the "usage" string.

Comment (kami619) [reply provision/rosa-cross-dc/cross-site-health-checks.sh:115]: thanks, thats a good catch Ryan. I have fixed it in my next commit.

**Review by ryanemerson — APPROVED** [review]
